import { HomeVideo } from '../types';

export const getHomeVideos = async (): Promise<HomeVideo[]> => {
  return [
    {
      id: '1',
      title: 'React Native Full Course',
      thumbnail: 'https://i.ytimg.com/vi/0-S5a0eXPoc/maxresdefault.jpg',
      channel: 'Programming Channel',
      views: 124000,
      duration: '12:30',
    },
    {
      id: '2',
      title: 'Build a YouTube Clone',
      thumbnail: 'https://i.ytimg.com/vi/9YffrCViTVk/maxresdefault.jpg',
      channel: 'Dev Tutorials',
      views: 82000,
      duration: '08:15',
    },
    {
      id: '3',
      title: 'Learn TypeScript in 1 Hour',
      thumbnail: 'https://i.ytimg.com/vi/BCg4U1FzODs/maxresdefault.jpg',
      channel: 'Code Academy',
      views: 310000,
      duration: '15:40',
    },
    {
      id: '4',
      title: 'Flutter Full Course 2024',
      thumbnail: 'https://i.ytimg.com/vi/uHNOqKdqQas/maxresdefault.jpg',
      channel: 'Tech Mastery',
      views: 245000,
      duration: '14:20',
    },
    {
      id: '5',
      title: 'Node.js Backend Tutorial',
      thumbnail: 'https://i.ytimg.com/vi/CcrC5zSv1iA/maxresdefault.jpg',
      channel: 'Learn With Code',
      views: 178000,
      duration: '09:45',
    },
    {
      id: '6',
      title: 'Python Data Science',
      thumbnail: 'https://i.ytimg.com/vi/hP931079TMw/maxresdefault.jpg',
      channel: 'Byte by Byte',
      views: 392000,
      duration: '18:10',
    },
    {
      id: '7',
      title: 'Swift iOS App Development',
      thumbnail: 'https://i.ytimg.com/vi/tVskbekONlw/maxresdefault.jpg',
      channel: 'Code Ninja',
      views: 95000,
      duration: '11:55',
    },
    {
      id: '8',
      title: 'CSS Grid and Flexbox Masterclass',
      thumbnail: 'https://i.ytimg.com/vi/0WjfKQdfeMU/maxresdefault.jpg',
      channel: 'Dev Hub',
      views: 267000,
      duration: '07:30',
    },
    {
      id: '9',
      title: 'JavaScript ES6+ Features',
      thumbnail: 'https://i.ytimg.com/vi/IBTx5aGj-6U/maxresdefault.jpg',
      channel: 'Programming Channel',
      views: 431000,
      duration: '13:25',
    },
    {
      id: '10',
      title: 'Django Web Framework Course',
      thumbnail: 'https://i.ytimg.com/vi/s950xhRvqYQ/maxresdefault.jpg',
      channel: 'Dev Tutorials',
      views: 156000,
      duration: '16:40',
    },
    {
      id: '11',
      title: 'Kotlin Android Development',
      thumbnail: 'https://i.ytimg.com/vi/_4uQI4ihGVU/maxresdefault.jpg',
      channel: 'Code Academy',
      views: 289000,
      duration: '10:15',
    },
    {
      id: '12',
      title: 'GraphQL with Apollo',
      thumbnail: 'https://i.ytimg.com/vi/UsfpzxZNsPo/maxresdefault.jpg',
      channel: 'Tech Mastery',
      views: 124000,
      duration: '08:50',
    },
    {
      id: '13',
      title: 'Docker and Kubernetes Basics',
      thumbnail: 'https://i.ytimg.com/vi/bB5eA7vU9W8/maxresdefault.jpg',
      channel: 'Learn With Code',
      views: 345000,
      duration: '20:05',
    },
    {
      id: '14',
      title: 'Machine Learning with TensorFlow',
      thumbnail: 'https://i.ytimg.com/vi/kQqrMNviM9U/maxresdefault.jpg',
      channel: 'Byte by Byte',
      views: 512000,
      duration: '22:30',
    },
    {
      id: '15',
      title: 'Vue.js Complete Guide',
      thumbnail: 'https://i.ytimg.com/vi/S26VdcWQzRQ/maxresdefault.jpg',
      channel: 'Code Ninja',
      views: 198000,
      duration: '12:45',
    },
    {
      id: '16',
      title: 'Angular for Beginners',
      thumbnail: 'https://i.ytimg.com/vi/63m2vvB4wo4/maxresdefault.jpg',
      channel: 'Dev Hub',
      views: 276000,
      duration: '09:20',
    },
    {
      id: '17',
      title: 'Svelte Tutorial',
      thumbnail: 'https://i.ytimg.com/vi/Sh5B7ApPh7k/maxresdefault.jpg',
      channel: 'Programming Channel',
      views: 89000,
      duration: '06:55',
    },
    {
      id: '18',
      title: 'Next.js 14 Crash Course',
      thumbnail: 'https://i.ytimg.com/vi/Y7nhXvJ7yH8/maxresdefault.jpg',
      channel: 'Dev Tutorials',
      views: 367000,
      duration: '14:10',
    },
    {
      id: '19',
      title: 'Tailwind CSS Full Tutorial',
      thumbnail: 'https://i.ytimg.com/vi/ovnyeq-Xxrc/maxresdefault.jpg',
      channel: 'Code Academy',
      views: 254000,
      duration: '11:35',
    },
    {
      id: '20',
      title: 'MongoDB Database Tutorial',
      thumbnail: 'https://i.ytimg.com/vi/Xm_VGeTpS2Q/maxresdefault.jpg',
      channel: 'Tech Mastery',
      views: 142000,
      duration: '15:50',
    },
    {
      id: '21',
      title: 'Firebase Authentication',
      thumbnail: 'https://i.ytimg.com/vi/CFI1ZnlHEFM/maxresdefault.jpg',
      channel: 'Learn With Code',
      views: 309000,
      duration: '07:40',
    },
    {
      id: '22',
      title: 'AWS Lambda Serverless',
      thumbnail: 'https://i.ytimg.com/vi/HXIHpDnsizk/maxresdefault.jpg',
      channel: 'Byte by Byte',
      views: 187000,
      duration: '13:15',
    },
    {
      id: '23',
      title: 'Cybersecurity Fundamentals',
      thumbnail: 'https://i.ytimg.com/vi/nQrUeK0n1qw/maxresdefault.jpg',
      channel: 'Code Ninja',
      views: 421000,
      duration: '17:25',
    },
    {
      id: '24',
      title: 'Git and GitHub Mastery',
      thumbnail: 'https://i.ytimg.com/vi/bP8mrNdR-hs/maxresdefault.jpg',
      channel: 'Dev Hub',
      views: 233000,
      duration: '08:30',
    },
    {
      id: '25',
      title: 'SQL for Data Analysis',
      thumbnail: 'https://i.ytimg.com/vi/SQTij8_Kwl4/maxresdefault.jpg',
      channel: 'Programming Channel',
      views: 165000,
      duration: '10:55',
    },
    {
      id: '26',
      title: 'Rust Programming Language',
      thumbnail: 'https://i.ytimg.com/vi/quoNVa88XfE/maxresdefault.jpg',
      channel: 'Dev Tutorials',
      views: 298000,
      duration: '19:40',
    },
    {
      id: '27',
      title: 'Go Lang Web Services',
      thumbnail: 'https://i.ytimg.com/vi/aP6w2OzidYM/maxresdefault.jpg',
      channel: 'Code Academy',
      views: 134000,
      duration: '12:20',
    },
    {
      id: '28',
      title: 'PHP Laravel Framework',
      thumbnail: 'https://i.ytimg.com/vi/Ubbb1RK7iFs/maxresdefault.jpg',
      channel: 'Tech Mastery',
      views: 203000,
      duration: '09:10',
    },
    {
      id: '29',
      title: 'WordPress Theme Development',
      thumbnail: 'https://i.ytimg.com/vi/KsHbs5RMVYU/maxresdefault.jpg',
      channel: 'Learn With Code',
      views: 176000,
      duration: '14:45',
    },
    {
      id: '30',
      title: 'SEO Techniques 2024',
      thumbnail: 'https://i.ytimg.com/vi/pCcblPDJDwc/maxresdefault.jpg',
      channel: 'Byte by Byte',
      views: 289000,
      duration: '06:25',
    },
    {
      id: '31',
      title: 'UI/UX Design Principles',
      thumbnail: 'https://i.ytimg.com/vi/UaB0gWFwuEU/maxresdefault.jpg',
      channel: 'Code Ninja',
      views: 412000,
      duration: '15:30',
    },
    {
      id: '32',
      title: 'Figma Tutorial for Developers',
      thumbnail: 'https://i.ytimg.com/vi/nGxpctRd2OQ/maxresdefault.jpg',
      channel: 'Dev Hub',
      views: 98000,
      duration: '11:05',
    },
    {
      id: '33',
      title: 'Three.js 3D Graphics',
      thumbnail: 'https://i.ytimg.com/vi/8TMQcRcBnW8/maxresdefault.jpg',
      channel: 'Programming Channel',
      views: 256000,
      duration: '18:15',
    },
    {
      id: '34',
      title: 'WebAssembly Introduction',
      thumbnail: 'https://i.ytimg.com/vi/WCGTQBCE3FA/maxresdefault.jpg',
      channel: 'Dev Tutorials',
      views: 145000,
      duration: '08:40',
    },
    {
      id: '35',
      title: 'Electron Desktop Apps',
      thumbnail: 'https://i.ytimg.com/vi/gQnBetuyktk/maxresdefault.jpg',
      channel: 'Code Academy',
      views: 321000,
      duration: '13:50',
    },
    {
      id: '36',
      title: 'Capacitor Mobile Plugins',
      thumbnail: 'https://i.ytimg.com/vi/AFkoZTEKOiM/maxresdefault.jpg',
      channel: 'Tech Mastery',
      views: 167000,
      duration: '10:30',
    },
    {
      id: '37',
      title: 'Expo React Native Advanced',
      thumbnail: 'https://i.ytimg.com/vi/lvFswfNez2o/maxresdefault.jpg',
      channel: 'Learn With Code',
      views: 234000,
      duration: '16:20',
    },
    {
      id: '38',
      title: 'TypeScript Advanced Types',
      thumbnail: 'https://i.ytimg.com/vi/oIx7ObcfdlU/maxresdefault.jpg',
      channel: 'Byte by Byte',
      views: 387000,
      duration: '07:55',
    },
    {
      id: '39',
      title: 'Redux Toolkit Tutorial',
      thumbnail: 'https://i.ytimg.com/vi/Y_JQti8YLn0/maxresdefault.jpg',
      channel: 'Code Ninja',
      views: 219000,
      duration: '09:35',
    },
    {
      id: '40',
      title: 'Zustand State Management',
      thumbnail: 'https://i.ytimg.com/vi/5zR1ZE5aqho/maxresdefault.jpg',
      channel: 'Dev Hub',
      views: 152000,
      duration: '05:45',
    },
    {
      id: '41',
      title: 'TanStack Query Explained',
      thumbnail: 'https://i.ytimg.com/vi/fyxoI-3cpEo/maxresdefault.jpg',
      channel: 'Programming Channel',
      views: 278000,
      duration: '12:10',
    },
    {
      id: '42',
      title: 'React Query vs TanStack Query',
      thumbnail: 'https://i.ytimg.com/vi/9X8n5s1z2jA/maxresdefault.jpg',
      channel: 'Dev Tutorials',
      views: 198000,
      duration: '10:50',
    },
    {
      id: '43',
      title: 'TanStack Query Caching',
      thumbnail: 'https://i.ytimg.com/vi/3X9n5s1z2jA/maxresdefault.jpg',
      channel: 'Code Academy',
      views: 234000,
      duration: '11:20',
    },
    {
      id: '44',
      title: 'TanStack Query Mutations',
      thumbnail: 'https://i.ytimg.com/vi/7X9n5s1z2jA/maxresdefault.jpg',
      channel: 'Tech Mastery',
      views: 167000,
      duration: '09:15',
    },
  ];
};
